name: Deploy
on:
  workflow_run:
    workflows: ['Unit Tests', 'E2E Tests']
    types:
      - completed
    branches: [main]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy 브랜치로 머지
        run: |
          git switch deploy
          git merge main --ff-only
          git push origin deploy --force
