name: Deploy
on:
  workflow_run:
    workflows: ['Unit Tests', 'E2E Tests']
    types:
      - completed
    branches: [main]
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy 브랜치로 머지
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin
          git switch deploy origin/deploy || git switch -c deploy
          git merge origin/main --ff-only
          git push origin deploy --force
