name: E2E Tests
on:
  workflow_run:
    workflows: ['Unit Tests']
    types:
      - completed
    branches: [main]
jobs:
  e2e-test:
    timeout-minutes: 60
    # 이 작업은 Unit 테스트가 성공한 후에만 실행됩니다.
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow.id == 'test-unit.yml'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # npm 캐시
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Playwright 캐시
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: 의존성 설치
        run: npm ci

      # 브라우저가 캐시되어 있지 않은 경우에만 설치
      - name: Playwright 브라우저 설치
        run: npx playwright install --with-deps chromium

      # Chromium만 사용하도록 설정
      - name: Playwright 테스트 실행
        env:
          CI: true
        run: npx playwright test --project=chromium --reporter=list

      # 테스트 결과 저장 (실패하거나 취소된 경우에도 저장)
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30
